spring:
  profiles:
    active: 9000
    include: base
  application:
    name: config-server-git
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456