spring:
  application:
    name: consumer-eureka-ribbon
server:
  port: 40020
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
stiger:
  cloud:
    producers:
      hello: http://producer-eureka