spring:
  application:
    name: consumer-eureka-ribbon
  task:
    scheduling:
      pool:
        size: 2
server:
  port: 40020
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
stiger:
  cloud:
    producers:
      hello: http://producer-eureka
      trace-a: http://trace-a
      trace-b: http://trace-b