spring:
  application:
    name: zipkin211
  profiles:
    include: base
    active: 60211
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    stream:
      bindings:
        output:
          destination: input
        stiger-topic:
          group: zipkin211
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
stiger:
  cloud:
    producers:
      zipkin311: http://zipkin311/access
      zipkin312: http://zipkin312/access
    nextServices: zipkin311,zipkin312