server:
  port: 20001
eureka:
  instance:
    hostname: point1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://master:20000/eureka/,http://point2:20002/eureka/