server:
  port: 20000
eureka:
  instance:
    hostname: master
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://point1:20001/eureka/,http://point2:20002/eureka/