spring:
  profiles:
    active: eureka
  application:
    name: turbine
server:
  port: 50002
turbine:
  app-config: consumer-eureka-feign,consumer-eureka-ribbon
  cluster-name-expression: new String("default")
  combine-host-port: true