spring:
  profiles:
    active: dev
  application:
    name: ${project.artifactId}
server:
  port: 10001
mybatis:
  configuration:
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl