spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: actadmin
        password: 123456
        instance:
          metadata:
            user.name: snake
            user.password: 123456
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sbs;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    schema: classpath*:sql/ddl.sql
    data: classpath*:sql/dml.sql
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: ${stiger.h2.console.root-path}/console
server:
  port: 10001
  servlet:
    session:
      timeout: 30M
stiger:
  h2:
    console:
      root-path: /h2