spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sbs;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    schema: classpath*:sql/ddl.sql
    data: classpath*:sql/dml.sql
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: ${stiger.h2.console.root-path}/console
stiger:
  h2:
    console:
      root-path: /h2