spring:
  application:
    name: ${project.artifactId}
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sbs;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    schema: classpath*:sql/ddl.sql
    data: classpath*:sql/dml.sql
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: ${stiger.h2.console.root-path}/console
server:
  port: 10001
logging:
  level:
    org.springframework.security: debug
mybatis:
  configuration:
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
stiger:
  h2:
    console:
      root-path: /h2