spring:
  profiles:
    active: ${proj.profile.id}
    include: base
  application:
    name: ${project.artifactId}-${proj.profile.id}-${server.port}
  jackson:
    serialization:
      INDENT_OUTPUT: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    parser:
      ALLOW_UNQUOTED_FIELD_NAMES: true