spring:
  profiles:
    active: dev
  application:
    name: ${project.artifactId}
  jackson:
    serialization:
      INDENT_OUTPUT: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    parser:
      ALLOW_UNQUOTED_FIELD_NAMES: true
mybatis:
  configuration:
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl