spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/StigerMallGoods?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: stigermall
    password: 123456