spring:
  profiles:
    active: 40010
    include: base
  application:
    name: consumer-eureka-feign
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
feign:
  hystrix:
    enabled: true
stiger:
  cloud:
    producers:
      hello: http://producer-eureka