spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/StigerMallOrder?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: stigermall
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456