server:
  port: 60321
spring:
  application:
    name: zipkin321
  profiles:
    include: base
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: refresh,bus-refresh