spring:
  application:
    name: consumer-eureka-feign-hystrix
  main:
    allow-bean-definition-overriding: true
server:
  port: 40004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream