server:
  port: 10000
spring:
  application:
    name: gateway-zuul
  profiles:
    include: base
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
zuul:
  routes:
    producer-eureka: /proEureka/**