spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: consumer-zookeeper
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
        register: false
server:
  port: 30020
stiger:
  cloud:
    producers:
      hello: http://producer-zookeeper