server:
  port: 8881
  servlet:
    context-path: /oauthClient
logging:
  level:
    org.springframework.security: DEBUG
spring:
  application:
    name: oauth2-client
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: fc6bdfe20592c3cc3e21
            client-secret: dac853bb50ef2497eed110d67fb95bb1bbbefbed
          demo:
            provider: demo-provider
            clientId: client1
            clientSecret: 123
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8881/oauthClient/login/oauth2/code/demo
            scope: any
        provider:
          demo-provider:
            authorization-uri: http://localhost:8880/oauthServer/oauth/authorize
            token-uri: http://localhost:8880/oauthServer/oauth/token
            user-info-uri: http://localhost:8880/oauthServer/user
            user-name-attribute: name
