server:
  port: 8881
  servlet:
    context-path: /oauthClient
logging:
  level:
    org.springframework.security: DEBUG
spring:
  application:
    name: oauth2-client
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: fc6bdfe20592c3cc3e21
            client-secret: dac853bb50ef2497eed110d67fb95bb1bbbefbed
            client-authentication-method: POST
          demo:
            provider: demo-provider
            clientId: client1
            clientSecret: 123
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8881/oauthClient/login/oauth2/code/demo
            scope: any
          gitee:
            provider: gitee-provider
            clientId: 99b417c143cc4e29f10b4417debb53b313a778d25edad42a667db2ff261605a9
            clientSecret: b880a42bba1351f52231d670499678be3e752965fd36ac4f13807841a2b556ff
            authorizationGrantType: authorization_code
            client-authentication-method: POST
            redirectUri: http://localhost:8881/oauthClient/login/oauth2/code/gitee
            scope: user_info
        provider:
          demo-provider:
            authorization-uri: http://localhost:8880/oauthServer/oauth/authorize
            token-uri: http://localhost:8880/oauthServer/oauth/token
            user-info-uri: http://localhost:8880/oauthServer/user
            user-name-attribute: name
          gitee-provider:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-info-authentication-method: GET
            user-name-attribute: name
