spring:
  cloud:
    stream:
      bindings:
        mall-bus-input:
          destination: mall-bus
        mall-bus-output:
          destination: mall-bus
      rabbit:
        bindings:
          mall-bus-input:
            consumer:
              auto-bind-dlq: true
stiger:
  mall:
    security:
      login-processing-url: /loginProcess
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkQN8OZ1D7m8CvE7EGi+Vho/gZEp6mk1cbFX6leJml82ZPIVDQ+f4HndbBA9qzDiwOsWFqySh5XO/A0GbuogylI9uvkTqQWT9P1SPFlyAVAkb2CJx9l+YorTv4ptOi4m09llg+wcbJreVRS2cmSVQ3OIsZ0JqUdbRVUcHLAaQJPzag+SlDp8DybfVGKw0R5Fy/wXohkSXZTTZfww9lJNxydGhdC/ckG5mXwoHxGRCa0olMLOzglH7mGBWyx5m0itknGR0lpu5xDUrXsWRb/2p1c/OYJdCpTanzXJaivfbmLlXfMpwfZgV2OI+YHTUPRINk1fDpgkyb6KrClhqTSlgWwIDAQAB
      private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCRA3w5nUPubwK8TsQaL5WGj+BkSnqaTVxsVfqV4maXzZk8hUND5/ged1sED2rMOLA6xYWrJKHlc78DQZu6iDKUj26+ROpBZP0/VI8WXIBUCRvYInH2X5iitO/im06LibT2WWD7Bxsmt5VFLZyZJVDc4ixnQmpR1tFVRwcsBpAk/NqD5KUOnwPJt9UYrDRHkXL/BeiGRJdlNNl/DD2Uk3HJ0aF0L9yQbmZfCgfEZEJrSiUws7OCUfuYYFbLHmbSK2ScZHSWm7nENStexZFv/anVz85gl0KlNqfNclqK99uYuVd8ynB9mBXY4j5gdNQ9Eg2TV8OmCTJvoqsKWGpNKWBbAgMBAAECggEAVxU8uGyUqs7HWcYDRaZlqNUl75Q6ZAcpBXXsca3v5iF1cD6m0lSvT7xlT97iR5mTWvfa+ZeaEWycvJvdpPq9RTGNU32XH4ZB/pINC2SpO83shrLItSdbRfpaRD73wBwGLBoofxcZWvrMDSsC64TZNowsFiZwKo1SUF/DEtEuJsc2+S5jmxT6L5zjZl6PaNMWtxl8hH6VDWBIfGLv2PK//lyo6OpVfSJoFmWYKEuBh4VLg9eG87oAmYGzmagOs+sfnkAiN4TXqL8xfuo8djV3tiIURCIq4IgsMfxoo0/QTzCT5Vi5VO9/tt5iIPhbfluhHbKgCFci5tPlNbRx8XR+4QKBgQDjCTHaEkWHZp309p0bnnOmydX6/OQTxWTaVQ2Vq9QdlBvXDoU1lMA6NrhpKQQAuqkne9n94fGLEiz6nrfw92Ryn8oK2a1LziNF1UShkpVqb8DqYBufIO0M7WxsDcoew7oR2kjFBepB42UM62g8Kac+bCMOf+UDtwaOCr0PVyYoxwKBgQCjg4KMepA/V8nzrZXqKzh+/tUZLveYizJjW8XNldWRqMLvVW+MNo/TlXuzl4cDTY54y2OXbGJ+L/WBg8YhKcjfqRWIDWNP0ivZUg8iZAQ37w/jx4MCLpZhzTUjixiI4PXH83KCZhxgyKu8CcHQDQW0Ab2Hn2UUHfYWHnsEH6B/zQKBgQCwpgbT1kOjBoUAhKHZS4BQ1dpYX0xW1c+S0XqwafGw0fyXaATdm8+1e74glHk42AOlZQhIMfTucEXu+m/EXbkaNpnNt3DO+qUXQMkVrifzmOBRfFYBimznEhS6PkB1j3THT0AvjFqoyXVmiAOiTAaE2z6rmXdnXJENE+3mcbiPIQKBgEFmp3/SwgFj9rXNl2nbMbSx7sAs5gGQo23UVjCdnpetHZMm4//8Dtj9MEYr9GegzLyJ9WKqilaYjiTodQXstZioA6GwYSmbEcjRppYF1R4eM4fS1Ba6VZH2xytZRk3xVL1OJV38w5r+iJokeO3jV4WhMJKfcYlzVmuQc3m5wLN9AoGAfm2dq2DGOwkzty+zW2YKf+Up/jIQwWVgvJzldQ2Mvn3+z5ZRyMEmig1RdMoClPt04BiyvJjuFM5uyxqFQMBPirq1EAcpfedd5N0Xo8KPf3Qvn+mSpDC5P+xIp/pk2LlmZxzXf/2EeLn2VnzSYgTMc6o62JX1t91xBPPMiCcUOQw=
      expiration-time: 30M
    service:
      router:
        account:
          url: 'http://mall-account'
        goods:
          url: 'http://mall-goods'
        order:
          url: 'http://mall-order'