spring:
  application:
    name: producer-eureka
  profiles:
    active: 30000
    include: base
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: refresh